### ISSUE TITLE
train/test_size meaning and usage is misleading.

### ISSUE THREAD

**Issue by msat59** [labdmitriy/ml-lab#4]
Hi @labdmitriy.

Thank you for your excellent job. However, the use of `train_size` and `test_size` in the way you've used doesn't make sense. In your code, `train_size` actually means `train_group_size`, however, it should be the number of samples in the training set from each group. I appreciate you if you implement that feature too.

Actually, I am working on such a dataset as you can in the image attached. I need to perform cross-validation with a let's say test_size=4 from each group. The code may need to handle the cases for which the split cannot be done so it should ignore them or add all to train (it can be defined by the user, as an argument).

Thank you

![image](https://github.com/labdmitriy/ml-lab/assets/20813541/ee03eff5-d846-45a7-a8e4-3300254636be)

**Comment by labdmitriy** [comment]
Hi,
I don’t support it anymore after I contributed this functionality to mlxtend, you can find documentation here: https://rasbt.github.io/mlxtend/user_guide/evaluate/GroupTimeSeriesSplit/
